export const SAVE_CLASS = "SAVE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const CHANGE_CUR_CLASS_LIST = "CHANGE_CUR_CLASS_LIST";

export const CHANGE_TABLE_OPEN_STATUS = "CHANGE_TABLE_OPEN_STATUS";

export const SAVE_EMPTY = "SAVE_EMPTY"
export const IS_EMPTY_STATUS = "IS_EMPTY_STATUS";