export const SAVE_CLASS = "SAVE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const CHANGE_CUR_CLASS_LIST = "CHANGE_CUR_CLASS_LIST";

export const CHANGE_TABLE_OPEN_STATUS = "CHANGE_TABLE_OPEN_STATUS";